spring.application.name=chat-poc
spring.datasource.url=jdbc:mysql://localhost:3306/ycyw_chat_poc
spring.datasource.username=root
spring.datasource.password=4u78b!DuCR?Y

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true