spring.application.name=chat-poc
spring.datasource.url=jdbc:mysql://localhost:3306/ycyw_chat_poc
spring.datasource.username=root
spring.datasource.password=#u1vDUM9nXf53z

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true